### PR TITLE
Add Dutch translations

### PR DESCRIPTION
**Pull request by sdiepend**

### CODE REVIEW

**Comment by jirikuncar** [comment]
@sdiepend please check the upstream repo https://github.com/mattupstate/flask-security/blob/develop/flask_security/translations/da_DK/LC_MESSAGES/flask_security.po

**Comment by sdiepend** [comment]
@jirikuncar I should call it flask_security.po and also do a PR on the upstream repo?

**Comment by jirikuncar** [comment]
@sdiepend yes. Please note, that it already exists.

**Comment by sdiepend** [comment]
@jirikuncar I don't see any dutch(netherlands & belgium) translations yet?

**Comment by jirikuncar** [comment]
Hups. Sorry, I confused it with Danish O:-). Please feel free to submit it as `flask_security/translations/nl_NL/LC_MESSAGES/flask_security.po` there. Thanks a lot!

**Pull request closed without merging**
