### PR TITLE
Added support for Pony ORM

### PR DESCRIPTION
**Pull request by jirikuncar**
Integrates mattupstate/flask-security#588

### CODE REVIEW

**Comment by willzfarmer** [comment]
So the tests are working, but I'm having issues with deploying... Here's the error I'm getting:

```
pony.orm.core.DatabaseSessionIsOver: Cannot load collection User[182].roles: the database session is over
```

**Comment by jirikuncar** [comment]
@willzfarmer I fear problems with https://github.com/inveniosoftware/flask-security-fork/pull/19/files#diff-b6ecf356247f63dd2551bb0fe512f014R83. Can you reproduce it as a new test case? I probably register the application teardown callback multiple times :(

**Comment by willzfarmer** [comment]
Ahh, my mistake... I installed from the wrong branch. That error isn't the real problem. I'm actually getting weird things like no attribute errors:

```
Traceback (most recent call last):
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/tornado/web.py", line 1446, in _execute
    result = self.prepare()
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/tornado/web.py", line 2706, in prepare
    self.fallback(self.request)
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/livereload/server.py", line 113, in __call__
    WSGIContainer.environ(request), start_response)
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/william/Dropbox/Projects/c/redirectserver/util.py", line 154, in db_session
    return wrapped(*args, **kwargs)
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/flask_login.py", line 790, in decorated_view
    elif not current_user.is_authenticated:
  File "/home/william/.virtualenvs/c/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'is_authenticated'
```

With user declaration

```python
class User(db.Entity):
    email = Required(str)
    username = Optional(str)
    password = Optional(str, nullable=True)
    last_login_at = Optional(datetime)
    current_login_at = Optional(datetime)
    last_login_ip = Optional(str)
    current_login_ip = Optional(str)
    login_count = Optional(int)
    active = Required(bool, default=True)
    confirmed_at = Optional(datetime)
    roles = Set(lambda: Role)
```

**Comment by jirikuncar** [comment]
@willzfarmer you are missing `flask_security:UserMixin` (see https://github.com/inveniosoftware/flask-security-fork/blob/master/flask_security/core.py#L337-L357).

**Comment by willzfarmer** [comment]
Ahh! I'm an idiot... Thanks for spotting that...

So I'll keep aggressively testing this, but as far as I can tell the decorator is working great. :+1:

**Comment by jirikuncar** [comment]
@willzfarmer please let me know when you consider it good enough for your production setup so I can merge it here. Thanks for testing 😉

**Comment by willzfarmer** [comment]
Quick note on this, when accessing `current_user` in a route method, you can't directly access its members since `current_user` is a proxy variable... Instead, each time I want to iterate over user roles, or other `Sets` (in PonyORM terms) I have to re-query to get the user instance like so:

```python
        cuser = orm.select(u for u in schema.User if u.id == current_user.id)[:][0]
        for r in cuser.roles:
            etc...
```

I'm not sure if the other ORMs require this sort of workaround, but it would be nice to get rid of it.

**Comment by jirikuncar** [comment]
@willzfarmer I am not an expert in PonyORM, but have you tried something like:

```python
user = current_user._get_current_object()
for role in user.roles:
    print(role)
```

**Pull request merged**
